export const nationalities = [
    { country: "Australia", code: "AU" },
    { country: "Brazil", code: "BR" },
    { country: "Canada", code: "CA" },
    { country: "Switzerland", code: "CH" },
    { country: "Germany", code: "DE" },
    { country: "Denmark", code: "DK" },
    { country: "Spain", code: "ES" },
    { country: "Finland", code: "FI" },
    { country: "France", code: "FR" },
    { country: "Great Britain", code: "GB" },
    { country: "Ireland", code: "IE" },
    { country: "India", code: "IN" },
    { country: "Iran", code: "IR" },
    { country: "Mexico", code: "MX" },
    { country: "Netherlands", code: "NL" },
    { country: "Norway", code: "NO" },
    { country: "New Zealand", code: "NZ" },
    { country: "Serbia", code: "RS" },
    { country: "Turkey", code: "TR" },
    { country: "Ukraine", code: "UA" },
    { country: "USA", code: "US" },
]